### ISSUE TITLE
Linux port

### ISSUE THREAD

**Issue by Dreamer2345** [Dreamer2345/Forge-Level-Editor#60]
Im looking into using Mono to port the program to linux atm.

https://www.mono-project.com/docs/gui/winforms/porting-winforms-applications/

If there are any points that need to be put across please do.

**Comment by Pharap** [comment]
For context:
* `add_` methods are the methods generated for when `+=` is used on an event,
* `set_` methods are methods generated for property setters. 

Is it just those 4 methods? If so, we might be able to figure out a workaround.
Tooltips probably won't be missed, but the other two might be an issue.
