### ISSUE TITLE
Change drawing interpolation to nearest neighbour

### ISSUE THREAD

**Issue by Pharap** [Dreamer2345/Forge-Level-Editor#67]
Nearest neighbour interpolation makes the map tiles look less blurry.

Without nearest neighbour:
![NoNearest](https://user-images.githubusercontent.com/2933055/83549300-01acbb80-a4fd-11ea-9a80-d1c1103b04a8.png)

With nearest neighbour:
![WithNearest](https://user-images.githubusercontent.com/2933055/83549292-ff4a6180-a4fc-11ea-88d0-3566131e8fa1.png)

To implement add `graphics.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.NearestNeighbor;` into `MapCollection.Draw` at any point before `CurrentMap.DrawBackground(graphics);`

**Comment by Dreamer2345** [comment]
Yea that seems better, Do you want to create a pull or I could?

**Comment by Pharap** [comment]
I was going to wait for @filmote's opinion as well so we're all on the same page,
but once we're all agreed anyone can make the PR.

Keep the issue open for now and close it when the PR that addresses it is merged using a [fixes/closes/resolves keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by Pharap** [comment]
Ah... you've already made a commit...

In that case we'll just have to assume @filmote's consent and backtrack if he's not happy with it.
