### ISSUE TITLE
Is DrawComponent needed?

### ISSUE THREAD

**Issue by Pharap** [Dreamer2345/Forge-Level-Editor#72]
I was having a look around when trying to make the naming more consistent (as per #71),
when it suddenly occurred to me that `DrawComponent` doesn't seem to be serving any purpose.

The other components inherit from it,
but `DrawComponent` itself is never used anywhere,
so that inheritance isn't actually doing anything useful.

Should we scrap `DrawComponent`?

**Comment by Dreamer2345** [comment]
Thats highly dependent on if this tool is used for something other than the components that are listed

**Comment by Pharap** [comment]
Even if it were, I can't see how `DrawComponent` would find use.
It's the kind of thing you'd find in a scene graph,
and the rendering in the editor isn't structured like a scene graph is.
(Although `System.Windows.Forms` works somewhat like a scene graph.)

**Comment by Dreamer2345** [comment]
Yep, it can be removed
